# Generated by Django 3.2 on 2021-08-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="link",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="event",
            name="link",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="newsitem",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="organization",
            name="title",
            field=models.CharField(max_length=150),
        ),
    ]
