# Generated by Django 3.2 on 2021-08-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_auto_20210801_1122"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="organization",
            field=models.ManyToManyField(
                related_name="events", to="community.Organization"
            ),
        ),
    ]
