# Generated by Django 3.2 on 2021-07-25 17:55

from django.db import migrations, models
import shortuuid


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_alter_event_poster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsitem",
            name="id",
            field=models.UUIDField(
                default=shortuuid.uuid(),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
