# Generated by Django 3.2 on 2021-08-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_alter_event_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="status",
        ),
        migrations.AddField(
            model_name="newsitem",
            name="status",
            field=models.CharField(
                choices=[("draft", "DRAFT"), ("public", "PUBLIC")],
                default="draft",
                max_length=12,
            ),
        ),
    ]
