# Generated by Django 3.2 on 2021-08-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0004_auto_20210815_0358"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsitem",
            name="status",
            field=models.CharField(
                choices=[("draft", "DRAFT"), ("public", "PUBLIC")],
                default="public",
                max_length=12,
            ),
        ),
    ]
