# Generated by Django 3.2 on 2021-07-26 17:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("community", "0004_alter_newsitem_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="newsitem",
            options={"base_manager_name": "objects"},
        ),
        migrations.AddField(
            model_name="newsitem",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_community.newsitem_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="newsitem",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
