# Generated by Django 3.2 on 2021-07-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20210726_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(default='', editable=False, unique=True),
        ),
    ]
