# Generated by Django 3.2 on 2021-08-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0006_auto_20210815_0402"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="link",
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
