# Generated by Django 3.2 on 2021-05-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0006_alter_event_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("preview", models.TextField(max_length=500)),
                ("publication_date", models.DateField()),
                ("link", models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="organization",
            field=models.ManyToManyField(to="community.Organization"),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[("finalized", "FINALIZED"), ("in planning", "IN PLANNING")],
                default="in planning",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="announcements",
            field=models.ManyToManyField(to="community.Announcement"),
        ),
    ]
