# Generated by Django 3.2 on 2021-08-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0007_auto_20210815_0404"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logo"),
        ),
        migrations.AddField(
            model_name="organization",
            name="profile_background",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_background"
            ),
        ),
    ]
