# Generated by Django 3.2 on 2021-05-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_auto_20210503_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_item_type', models.CharField(choices=[('announcement', 'ANNOUNCEMENT'), ('events', 'EVENTS')], max_length=30)),
            ],
        ),
    ]
