# Generated by Django 3.2 on 2021-08-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0008_auto_20210815_0412"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="preview",
        ),
        migrations.AddField(
            model_name="announcement",
            name="excerpt",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
