# Generated by Django 3.2 on 2021-08-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0009_auto_20210815_0417"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="announcements",
        ),
        migrations.AddField(
            model_name="newsitem",
            name="organizations",
            field=models.ManyToManyField(to="community.Organization"),
        ),
    ]
