# Generated by Django 3.2 on 2021-10-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_newsitem_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='status',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('public', 'PUBLIC'), ('cancelled', 'CANCELLED')], default='public', max_length=12),
        ),
    ]
